In [43]:
!pip install nltk

In [44]:
corpus = "Hello myself deepak Kumar. You are Watching NLP Tutorial! please complete the entire course."

In [45]:
from nltk.tokenize import sent_tokenize

In [46]:
import nltk
nltk.download('punkt')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!


True

In [47]:
documents = sent_tokenize(corpus)

In [48]:
documents

['Hello myself deepak Kumar.',
 'You are Watching NLP Tutorial!',
 'please complete the entire course.']

In [49]:
from nltk.tokenize import word_tokenize

In [50]:
word_tokenize = word_tokenize(corpus)
word_tokenize

['Hello',
 'myself',
 'deepak',
 'Kumar',
 '.',
 'You',
 'are',
 'Watching',
 'NLP',
 'Tutorial',
 '!',
 'please',
 'complete',
 'the',
 'entire',
 'course',
 '.']

In [51]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [52]:
df = pd.read_csv("movies_metadata.csv")

/tmp/ipykernel_11893/1650877637.py:1: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("movies_metadata.csv")


In [53]:
df.head()

,adult,belongs_to_collection,budget,genres,homepage,id,imdb_id,original_language,original_title,overview,...,release_date,revenue,runtime,spoken_languages,status,tagline,title,video,vote_average,vote_count
0,False,"{'id': 10194, 'name': 'Toy Story Collection', ...",30000000,"[{'id': 16, 'name': 'Animation'}, {'id': 35, '...",http://toystory.disney.com/toy-story,862,tt0114709,en,Toy Story,"Led by Woody, Andy's toys live happily in his ...",...,1995-10-30,373554033.0,81.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,NaN,Toy Story,False,7.7,5415.0
1,False,NaN,65000000,"[{'id': 12, 'name': 'Adventure'}, {'id': 14, '...",NaN,8844,tt0113497,en,Jumanji,When siblings Judy and Peter discover an encha...,...,1995-12-15,262797249.0,104.0,"[{'iso_639_1': 'en', 'name': 'English'}, {'iso...",Released,Roll the dice and unleash the excitement!,Jumanji,False,6.9,2413.0
2,False,"{'id': 119050, 'name': 'Grumpy Old Men Collect...",0,"[{'id': 10749, 'name': 'Romance'}, {'id': 35, ...",NaN,15602,tt0113228,en,Grumpier Old Men,A family wedding reignites the ancient feud be...,...,1995-12-22,0.0,101.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Still Yelling. Still Fighting. Still Ready for...,Grumpier Old Men,False,6.5,92.0
3,False,NaN,16000000,"[{'id': 35, 'name': 'Comedy'}, {'id': 18, 'nam...",NaN,31357,tt0114885,en,Waiting to Exhale,"Cheated on, mistreated and stepped on, the wom...",...,1995-12-22,81452156.0,127.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Friends are the people who let you be yourself...,Waiting to Exhale,False,6.1,34.0
4,False,"{'id': 96871, 'name': 'Father of the Bride Col...",0,"[{'id': 35, 'name': 'Comedy'}]",NaN,11862,tt0113041,en,Father of the Bride Part II,Just when George Banks has recovered from his ...,...,1995-02-10,76578911.0,106.0,"[{'iso_639_1': 'en', 'name': 'English'}]",Released,Just When His World Is Back To Normal... He's ...,Father of the Bride Part II,False,5.7,173.0


In [54]:
df.duplicated().sum()

np.int64(13)

In [55]:
df.isnull().sum()

,0
adult,0
belongs_to_collection,40972
budget,0
genres,0
homepage,37684
id,0
imdb_id,17
original_language,11
original_title,0
overview,954


In [56]:
df.shape

(45466, 24)

In [57]:
df = df.drop_duplicates().reset_index(drop=True)

In [58]:
df.columns

Index(['adult', 'belongs_to_collection', 'budget', 'genres', 'homepage', 'id',
       'imdb_id', 'original_language', 'original_title', 'overview',
       'popularity', 'poster_path', 'production_companies',
       'production_countries', 'release_date', 'revenue', 'runtime',
       'spoken_languages', 'status', 'tagline', 'title', 'video',
       'vote_average', 'vote_count'],
      dtype='object')

In [59]:
relevant_columns = ['title', 'genres','tagline', 'overview', 'popularity', 'vote_average']
print(relevant_columns)

['title', 'genres', 'tagline', 'overview', 'popularity', 'vote_average']


In [60]:
df1 = df[['title', 'genres', 'tagline', 'overview', 'popularity', 'vote_average']]

In [61]:
df1.shape

(45453, 6)

In [62]:
df1.isnull().sum()

,0
title,6
genres,0
tagline,25045
overview,954
popularity,5
vote_average,6


In [63]:
df1 = df1.dropna(subset=['title'])

In [64]:
df1['overview'] = df1['overview'].fillna(' ')

In [65]:
df1.isnull().sum()

,0
title,0
genres,0
tagline,25039
overview,0
popularity,0
vote_average,0


In [66]:
import ast

df1['genres'] = df1['genres'].fillna('[]')
df1['genres'] = df1['genres'].apply(lambda x: ' '.join([item['name'] for item in (ast.literal_eval(x) if x.strip() and x != 'nan' else [])]))

In [67]:
df1['tagline'] = df1['tagline'].fillna(' ')

In [68]:
df1.isnull().sum()

,0
title,0
genres,0
tagline,0
overview,0
popularity,0
vote_average,0


In [69]:
df1.isnull().sum()

,0
title,0
genres,0
tagline,0
overview,0
popularity,0
vote_average,0


In [70]:
df1.head()

,title,genres,tagline,overview,popularity,vote_average
0,Toy Story,Animation Comedy Family,,"Led by Woody, Andy's toys live happily in his ...",21.946943,7.7
1,Jumanji,Adventure Fantasy Family,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,17.015539,6.9
2,Grumpier Old Men,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,11.7129,6.5
3,Waiting to Exhale,Comedy Drama Romance,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",3.859495,6.1
4,Father of the Bride Part II,Comedy,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,8.387519,5.7


In [71]:
df1['tags'] = df1['genres'] + ' ' + df1['tagline'] + ' ' + df1['overview']

In [72]:
df1.head()

,title,genres,tagline,overview,popularity,vote_average,tags
0,Toy Story,Animation Comedy Family,,"Led by Woody, Andy's toys live happily in his ...",21.946943,7.7,"Animation Comedy Family Led by Woody, Andy's..."
1,Jumanji,Adventure Fantasy Family,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,17.015539,6.9,Adventure Fantasy Family Roll the dice and unl...
2,Grumpier Old Men,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,11.7129,6.5,Romance Comedy Still Yelling. Still Fighting. ...
3,Waiting to Exhale,Comedy Drama Romance,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",3.859495,6.1,Comedy Drama Romance Friends are the people wh...
4,Father of the Bride Part II,Comedy,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,8.387519,5.7,Comedy Just When His World Is Back To Normal.....


In [73]:
import nltk
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [74]:
nltk.download('stopwords')
nltk.download('wordnet')
import re

[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data]   Package wordnet is already up-to-date!


In [75]:
stopwords = set(stopwords.words('english'))
lemmatizer = WordNetLemmatizer()

In [76]:
def preprocessing(text):
  text = text.lower()
  text = re.sub(r'[^a-zA-Z0-9\s]', '', text)
  word = text.split()
  word = [word for word in word if word not in stopwords]
  word = [lemmatizer.lemmatize(word) for word in word]
  text = ' '.join(word)
  return text

In [77]:
df1['tags'][0]

"Animation Comedy Family   Led by Woody, Andy's toys live happily in his room until Andy's birthday brings Buzz Lightyear onto the scene. Afraid of losing his place in Andy's heart, Woody plots against Buzz. But when circumstances separate Buzz and Woody from their owner, the duo eventually learns to put aside their differences."

In [78]:
df1['tags'] = df1['tags'].apply(preprocessing)

In [79]:
df1['tags'][0]

'animation comedy family led woody andys toy live happily room andys birthday brings buzz lightyear onto scene afraid losing place andys heart woody plot buzz circumstance separate buzz woody owner duo eventually learns put aside difference'

In [80]:
df1.head()

,title,genres,tagline,overview,popularity,vote_average,tags
0,Toy Story,Animation Comedy Family,,"Led by Woody, Andy's toys live happily in his ...",21.946943,7.7,animation comedy family led woody andys toy li...
1,Jumanji,Adventure Fantasy Family,Roll the dice and unleash the excitement!,When siblings Judy and Peter discover an encha...,17.015539,6.9,adventure fantasy family roll dice unleash exc...
2,Grumpier Old Men,Romance Comedy,Still Yelling. Still Fighting. Still Ready for...,A family wedding reignites the ancient feud be...,11.7129,6.5,romance comedy still yelling still fighting st...
3,Waiting to Exhale,Comedy Drama Romance,Friends are the people who let you be yourself...,"Cheated on, mistreated and stepped on, the wom...",3.859495,6.1,comedy drama romance friend people let never l...
4,Father of the Bride Part II,Comedy,Just When His World Is Back To Normal... He's ...,Just when George Banks has recovered from his ...,8.387519,5.7,comedy world back normal he surprise life geor...


In [81]:
df1 = df1.reset_index(drop=True)

In [82]:
indices = pd.Series(df.index, index=df['title']).drop_duplicates()

In [83]:
indices

,0
title,
Toy Story,0
Jumanji,1
Grumpier Old Men,2
Waiting to Exhale,3
Father of the Bride Part II,4
...,...
Subdue,45448
Century of Birthing,45449
Betrayal,45450


In [84]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [85]:
tfidf = TfidfVectorizer(max_features=50000,stop_words='english',ngram_range=(1,2))


In [86]:
tfidf_matrix = tfidf.fit_transform(df1['tags'])

In [87]:
tfidf_matrix.shape

(45447, 50000)

In [88]:
print(tfidf_matrix.toarray())

[[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [89]:
from sklearn.metrics.pairwise import linear_kernel

In [94]:
def recomend(title,n = 10):
  if title not in indices:
    return ['Movie not found']
  idx = indices[title]
  sim_score = linear_kernel(tfidf_matrix[idx],tfidf_matrix).flatten()
  similar_idx = sim_score.argsort()[::-1][1:n+1]

  return df['title'].iloc[similar_idx]

In [98]:
recomend('Waiting to Exhale')

,title
21451,Sunset Strip
31048,Punishment Room
18497,Woman in Love
30081,Survivor
17545,Souls for Sale
27325,Phantom Punch
16015,Heartbreaker
14270,The Divorce of Lady X
37390,A Journey Through Fairyland
27575,Human Touch


In [99]:
import pickle

pickle.dump(tfidf_matrix, open('tfidf_matrix.pkl', 'wb'))

pickle.dump(tfidf,open('tfidf.pkl','wb'))

df.to_pickle('df.pkl')

pickle.dump(indices,open('indices.pkl','wb'))
