In [ ]:
texts = [
    "I love coding",
    "Python is great",
    "This movie is amazing",
    "I feel happy",
    "The food is tasty",
    "Today is wonderful",
    "She is brilliant",
    "I enjoy learning",
    "The game was fun",
    "Life is beautiful",

    "I hate bugs",
    "This movie is boring",
    "I feel sad",
    "The food is awful",
    "Today is terrible",
    "She is rude",
    "I am frustrated",
    "The game was bad",
    "Life is difficult",
    "The service was poor",

    "Machine learning rocks",
    "Deep learning works",
    "The project succeeded",
    "The model is accurate",
    "I passed the exam",
    "The app runs smoothly",
    "The result is excellent",

    "The project failed",
    "The model is wrong",
    "I failed the exam",
    "The app crashed",
    "The result is disappointing",
    "The network is slow"
]

In [ ]:
labels = [
    1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
    1, 1, 1, 1, 1, 1, 1,
    0, 0, 0, 0, 0, 0
]

In [ ]:
from typing_extensions import Sequence
from tensorflow.keras.preprocessing.text import Tokenizer
from tensorflow.keras.preprocessing.sequence import pad_sequences

tokanizer = Tokenizer(oov_token="<OOV>")
tokanizer.fit_on_texts(texts)

Sequence = tokanizer.texts_to_sequences(texts)
padded = pad_sequences(Sequence, padding="post")

word_index = tokanizer.word_index
vocab_size = len(word_index) + 1 # Added +1 to account for the highest index
print(word_index)
print(vocab_size)
print(padded)

{'<OOV>': 1, 'is': 2, 'the': 3, 'i': 4, 'learning': 5, 'was': 6, 'this': 7, 'movie': 8, 'feel': 9, 'food': 10, 'today': 11, 'she': 12, 'game': 13, 'life': 14, 'project': 15, 'model': 16, 'exam': 17, 'app': 18, 'result': 19, 'failed': 20, 'love': 21, 'coding': 22, 'python': 23, 'great': 24, 'amazing': 25, 'happy': 26, 'tasty': 27, 'wonderful': 28, 'brilliant': 29, 'enjoy': 30, 'fun': 31, 'beautiful': 32, 'hate': 33, 'bugs': 34, 'boring': 35, 'sad': 36, 'awful': 37, 'terrible': 38, 'rude': 39, 'am': 40, 'frustrated': 41, 'bad': 42, 'difficult': 43, 'service': 44, 'poor': 45, 'machine': 46, 'rocks': 47, 'deep': 48, 'works': 49, 'succeeded': 50, 'accurate': 51, 'passed': 52, 'runs': 53, 'smoothly': 54, 'excellent': 55, 'wrong': 56, 'crashed': 57, 'disappointing': 58, 'network': 59, 'slow': 60}
61
[[ 4 21 22  0]
 [23  2 24  0]
 [ 7  8  2 25]
 [ 4  9 26  0]
 [ 3 10  2 27]
 [11  2 28  0]
 [12  2 29  0]
 [ 4 30  5  0]
 [ 3 13  6 31]
 [14  2 32  0]
 [ 4 33 34  0]
 [ 7  8  2 35]
 [ 4  9 36  0]
 

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Embedding, Flatten, Dense, SimpleRNN

In [ ]:
model = Sequential()
model.add(Embedding(vocab_size, 8, input_length=padded.shape[1]))
model.add(SimpleRNN(units=8, activation="tanh"))

model.add(Dense(3,activation='softmax'))

/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/embedding.py:100: UserWarning: Argument `input_length` is deprecated. Just remove it.
  warnings.warn(


In [ ]:
import numpy as np
X  = np.array(padded)
y = np.array(labels)

In [ ]:
model.compile(loss='sparse_categorical_crossentropy', optimizer='adam', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_4"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ embedding_4 (Embedding)         │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ simple_rnn_2 (SimpleRNN)        │ ?                      │   0 (unbuilt) │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_2 (Dense)                 │ ?                      │   0 (unbuilt) │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 0 (0.00 B)

 Trainable params: 0 (0.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
history = model.fit(X, y, epochs=20,batch_size = 4,verbose=1)

Epoch 1/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 2s 7ms/step - accuracy: 0.2727 - loss: 1.0974    
Epoch 2/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.3939 - loss: 1.0602 
Epoch 3/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.5455 - loss: 1.0246 
Epoch 4/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4848 - loss: 0.9886 
Epoch 5/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4848 - loss: 0.9506 
Epoch 6/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4848 - loss: 0.9119 
Epoch 7/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4848 - loss: 0.8763 
Epoch 8/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4848 - loss: 0.8460 
Epoch 9/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.4848 - loss: 0.8194 
Epoch 10/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4848 - loss: 0.7949 
Epoch 11/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4848 - loss: 0.7768 
Epoch 12/20
9/9 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.4848 - loss: 0.7618